---
title: "OptimalCutoff_in_coxph"
author: "png"

# for pdf
toc: true

number-sections: true
highlight-style: pygments

format:
  html:
    code-fold: false
    code-tools: true
    code-link: true
    code-line-numbers: true
    
    df-print: paged # default, kable, tibble, paged
    
    html-math-method: katex
    
    # for pdf
    geometry: 
      - top=30mm
      - left=30mm
    
editor: visual
execute:
  echo: true
  warning: false
  include: true
  message: false
  cache: true
---

# Library

```{r}
#| label: load-packages

library(survival)
library(tidyverse)
library(MatchIt)

```

# Data Preprocessing

```{r}

# Load data
df <- iris

print(dim(df))


```


# EDA

## Subtitle 1

```{r}
#| label: fig-scatterplot
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-alt: "Scatterplot of city vs. highway mileage for cars, where points are colored by the number of cylinders. The plot displays a positive, linear, and strong relationship between city and highway mileage, and mileage increases as the number cylinders decreases."
#| fig-width: 6
#| fig-height: 3.5
#| column: page-right

plot( df[,1:2] )

```

\@fig-scatterplot shows a positive, strong, and linear relationship between the city and highway mileage of these cars.


# Multiple plots

```{r}
#| label: fig-mpg
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-subcap:
#|   - "Color by number of cylinders"
#|   - "Color by engine displacement, in liters"
#| layout-ncol: 2
#| column: page

plot( df[,1:2] )
plot( df[,2:3] )

```

# echo = FALSE

```{r}
#| echo: false

df.n <- round(nrow(df), 2)
df.p <- round(ncol(df), 2)
```

- There are `r nrow(df)` observations in our data. `r df.n` and `r df.p`.


# Equation

$y = x + e$

$$
Y = X B A^\top
$$
